language: node_js
node_js: '12'
install: npm install
addons:
  sonarcloud:
    organization: 'open-cluster-management'
  token:
    secure: "${SONAR_TOKEN}"
        
jobs:
  include:
    - stage: Pull Request
      if: type = pull_request
      script:
        - npm run lint
        - npm test
        - make sonar/js/jest-init
        - make sonar/js
                
    - stage: Build and Publish
      if: type = push AND branch = main
      script:
        - npm test &&
          npm run build &&
          scripts/publish.sh &&
          sonar-scanner
