# Copyright Contributors to the Open Cluster Management project

language: node_js
node_js: '14'
install: npm install
addons:
    sonarcloud:
        organization: 'open-cluster-management'
jobs:
    include:
        - stage: Pull Request
          if: type = pull_request
          script: npm run build && npm test
