language: node_js
node_js: '12'
install: npm install
addons:
    sonarcloud:
        organization: 'open-cluster-management'
jobs:
    include:
        - stage: Pull Request
          if: type = pull_request
          script:
              - npm test &&
                npm run lint &&
                npm run build

        - stage: Build and Publish
          if: type = push AND branch = main
          script:
              - npm test &&
                npm run build &&
                scripts/publish.sh &&
                sonar-scanner
