language: node_js
node_js: '12'
install: npm install
addons:
    sonarcloud:
        organization: 'open-cluster-management'
jobs:
    include:
        - stage: unit-test
          if: type = pull_request
          script:
            - make sonar/js/jest-init
            - npm test &&
              npm run lint
            - make sonar/js

        - stage: Build and Publish
          if: type = push AND branch = main
          script:
              - npm test &&
                npm run build &&
                scripts/publish.sh &&
                sonar-scanner
