language: node_js
node_js: '12'
install: npm install
addons:
  sonarcloud:
    organization: 'open-cluster-management'
    token:
      secure: "${SONAR_TOKEN}"

stages:
  - build
  - unit-test
        
jobs:
  include:
    - stage: unit-test
      name: "Run unit tests"
      if: type = pull_request
      script:
        # Set the image tag differently for PRs
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        # Bootstrap the build harness, pull test image, and run unit tests.
        - make
        - make sonar/js/jest-init
        - npm test
        - make sonar/js
                
    - stage: build
      if: type = push AND branch = main
      script:
        - npm test &&
          npm run build &&
          scripts/publish.sh &&
          sonar-scanner
